version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: easypay-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "EasyPay@Sql2024!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost",
             "-U", "sa", "-P", "EasyPay@Sql2024!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easypay-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;Database=EasyPayDB;
        User Id=sa;Password=EasyPay@Sql2024!;
        TrustServerCertificate=True;
      JwtSettings__SecretKey: "EasyPay@Hexaware#SecretKey$2024!SuperSecureKeyForJWT256BitMinimum"
      JwtSettings__Issuer: "EasyPay.API"
      JwtSettings__Audience: "EasyPay.Client"
      JwtSettings__AccessTokenMinutes: "60"
      JwtSettings__RefreshTokenDays: "7"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sqlserver-data:
